spring.application.name=auth-api
server.port=${APP_PORT:8080}
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.url=jdbc:sqlite:${AUTH_DB_PATH:/data/auth.db}
spring.jpa.hibernate.ddl-auto=update
